[package]
name = "dozer-ingestion-snowflake"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dozer-ingestion-connector = { path = "../connector" }
odbc = "0.17.0"
include_dir = "0.7.3"
genawaiter = "0.99.1"
memchr = "2.6.4"
rand = "0.8.5"
