[package]
name = "dozer-ingestion-ethereum"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dozer-ingestion-connector = { path = "../connector" }
web3 = "0.18.0"
hex-literal = "0.4.1"
dozer-tracing = { path = "../../dozer-tracing" }
