[workspace]
members = [
  "dozer-api",
  "dozer-ingestion",
  "dozer-types",
  "dozer-storage",
  "dozer-core",
  "dozer-orchestrator",
  "dozer-sql",
  "dozer-cache",
  "dozer-tracing",
  "dozer-tests",
  "dozer-log",
  "dozer-log-js",
  "dozer-utils",
  "dozer-admin"
]
exclude = ["dozer-ingestion/tests/**/**", "config/**/**"]

[patch.crates-io]
postgres = { git = "https://github.com/getdozer/rust-postgres" }
postgres-protocol = { git = "https://github.com/getdozer/rust-postgres" }
postgres-types = { git = "https://github.com/getdozer/rust-postgres" }
tokio-postgres = { git = "https://github.com/getdozer/rust-postgres" }
