[package]
name = "dozer-ingestion-kafka"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dozer-ingestion-connector = { path = "../connector" }
rdkafka = "0.34.0"
schema_registry_converter = { version = "4.0", features = ["avro"] }
base64 = "0.21.0"
