[package]
name = "dozer-ingestion-oracle"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dozer-ingestion-connector = { path = "../connector" }
fxhash = "0.2.1"
memchr = "2.7.2"
oracle = { version = "0.5.7", features = ["chrono", "stmt_without_lifetime"] }
regex = "1.10.3"

[dev-dependencies]
env_logger = "0.11.1"
