services:
  dozer-connector-tests:
    build: .
    image: dozer-connector-tests
    volumes:
      - ${PWD}:${PWD}
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: ${PWD}
    environment:
      - ETH_WSS_URL
      - ETH_HTTPS_URL
      - RUST_LOG=info
      - DOZER_VERSION
