[package]
name = "dozer-api"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-web-httpauth = "0.8.0"
actix-cors = "0.6.3"
dozer-cache = {path = "../dozer-cache"}
dozer-types = {path = "../dozer-types"}
dozer-tracing = {path = "../dozer-tracing"}
handlebars = "4.3.5"
tempdir = "0.3.7"
openapiv3 = "1.0.1"
tonic-build = "0.8.2"
tokio = { version = "1", features = ["full"] }
tonic = {version = "0.8.3"}
prost = "0.11.0"
prost-reflect = { version = "0.9.2", features = ["serde", "text-format"] } 
tonic-reflection = "0.6.0"
Inflector = "0.11.4"
futures-util = "0.3.25"
prost-build = "0.11.5"
tonic-web = "0.4.0"
jsonwebtoken = "8.2.0"
tokio-stream = "0.1.11"
crossbeam = "0.8.2"
async-trait = "0.1.58"
tracing-actix-web = "0.7.1"
tower = "0.4.13"
hyper = "0.14.23"
actix-http = "3.2.2"


[build-dependencies]
tonic-build = "0.8"
