[package]
name = "dozer-ingestion-grpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dozer-ingestion-connector = { path = "../connector" }
dozer-services = { path = "../../dozer-services" }
tower-http = { version = "0.4", features = ["full"] }
tonic-web = "0.10.2"
tonic-reflection = "0.10.0"
