[package]
name = "dozer-ingestion-postgres"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dozer-ingestion-connector = { path = "../connector" }
postgres-protocol = "0.6.4"
postgres-types = { version = "0.2.4", features = [
    "with-serde_json-1",
    "with-uuid-1",
] }
tokio-postgres = { version = "0.7.7", features = [
    "with-chrono-0_4",
    "with-geo-types-0_7",
    "with-uuid-1",
] }
uuid = { version = "1.3.1", features = ["serde", "v4"] }
rustls = { version = "0.21.7", features = ["dangerous_configuration"] }
tokio-postgres-rustls = "0.10.0"
rustls-native-certs = "0.6.3"
regex = "1"
rand = "0.8.5"

[dev-dependencies]
serial_test = "1.0.0"
