app_name: dozer-eth-dashboard
connections:
  - config: !Ethereum
      provider: !Trace
        https_url: "{{ETH_HTTPS_URL}}"
        from_block: 1000000
        to_block: 1000000
        batch_size: 3
    name: eth_conn1

sources:
  - name: traces
    table_name: eth_traces
    connection: eth_conn1

endpoints:
  - name: traces
    path: /traces
    table_name: traces
    index:
