[package]
name = "dozer-ingestion-object-store"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dozer-ingestion-connector = { path = "../connector" }
object_store = { version = "0.7.1", features = ["aws"] }
url = "2.4.1"
datafusion = { workspace = true }
