[package]
name = "dozer-ingestion-javascript"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_ast = "0.29.5"
deno_runtime = "0.129.0"
dozer-ingestion-connector = { path = "../connector" }

[dev-dependencies]
camino = "1.1.6"
