[package]
name = "dozer-ingestion-javascript"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dozer-ingestion-connector = { path = "../connector" }
dozer-deno = { path = "../../dozer-deno" }

[dev-dependencies]
camino = "1.1.6"
