app_name: sql-window-functions-sample

connections:
  - config : !LocalStorage
      details:
        path: data
      tables:
        - !Table
          name: yellow_trips
          config: !Parquet
            path: yellow_trips
            extension: .parquet
    name: yellow_taxi

sql: |
  SELECT t.PULocationID as location, t.tpep_pickup_datetime as pickup_time, t.window_start as start, t.window_end AS end
  INTO tumble
  FROM TUMBLE(yellow_trips, tpep_pickup_datetime, '5 MINUTES') t;

  SELECT t.PULocationID as location, t.tpep_pickup_datetime as pickup_time, t.window_start as start, t.window_end AS end
  INTO hop
  FROM HOP(yellow_trips, tpep_pickup_datetime, '1 MINUTE', '2 MINUTES') t;

sources:
  - name: yellow_trips
    table_name: yellow_trips
    connection: yellow_taxi

endpoints:
  - name: tumble
    path: /tumble
    table_name: tumble
  - name: hop
    path: /hop
    table_name: hop

cache_max_map_size: 2147483648
