connections:    
  - config : !LocalStorage
      details:
        path: data
      tables:
        - !Table
          name: taxi_zone_lookup
          config: !CSV
            path: zones
            extension: .csv
        - !Table
          name: yellow_trips
          config: !Parquet
            path: yellow_trips
            extension: .parquet
    name: yellow_taxi

sql: |
  SELECT t.tpep_pickup_datetime AS pickup_time, z.Zone AS zone
  INTO pickup
  FROM yellow_trips t JOIN taxi_zone_lookup z ON t.PULocationID = z.LocationID;

sources:
  - name: taxi_zone_lookup
    table_name: taxi_zone_lookup
    connection: !Ref yellow_taxi
    columns:
  - name: yellow_trips
    table_name: yellow_trips
    connection: !Ref yellow_taxi
    columns:

endpoints:
  - name: pickup
    path: /pickup
    table_name: pickup
    index:
      primary_key: 

cache_max_map_size: 2147483648
