[package]
name = "dozer-ingestion-deltalake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dozer-ingestion-connector = { path = "../connector" }
dozer-ingestion-object-store = { path = "../object-store" }
deltalake = { version = "0.16.2", default-features = false, features = [
    "datafusion",
] }
